import '../scss/style.scss'
import '../scss/modals.scss'
import '../scss/swipers.scss'
import '../scss/aside.scss'

import '../scss/brands.scss'
import '../scss/devices.scss'
import '../scss/service.scss'
import '../scss/footer.scss'
import './expandableBlocks.js'
import './swipers.js'
import './asideMenu.js'
import './modals.js'
